### ISSUE TITLE
add changes based on the newbury workshop

### ISSUE THREAD

**Issue by jmailhot** [AMWA-TV/nmos-audio-channel-mapping#21]
based on the newbury workshop the following changes should be made:
* add a new resource /map/active/{outputId} (GET) which returns only the map fragment associated with the specified output
* add documentation about using version update of the source when an output changes - if the output has an associated nmos source, and otherwise updating the related device version as a form of notification.

**Comment by jmailhot** [comment]
see pull request #22

**Comment by andrewbonney** [comment]
Closing as the PR was merged
