### ISSUE TITLE
Do not force receivers to trace back their connected source

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-audio-channel-mapping#23]
Hi,

As we discussed during the workshop with other IS-08 participants I think it's too much to ask of an audio receiver to force it to trace its incoming source using the IS-04 query mechanism. The control system has this information readily available anyway as it needs to keep track of the whole system.

The section I am referring to is this:

> Receiver / Source and Input Relationship
Where the audio associated with an Audio Channel Mapping API Input comes directly from an NMOS Receiver, the UUID of the originating Source SHOULD be populated in id field of the parent resource, and the type filed set to source. This information may be made available using in-stream identifiers, or some sidecar method of reception.

> {
  "id": "bdec047b-d161-492a-9496-96da704de2b1",
  "type": "source"
}

I think this should be removed entirely.

**Comment by simonrankine** [comment]
Fixed in #24

**Comment by andrewbonney** [comment]
Closing as the PR was merged
