### ISSUE TITLE
description in example file should be 2110-30 instead of 2110-20

### ISSUE THREAD

**Issue by thosil** [AMWA-TV/nmos-audio-channel-mapping#34]
In the file "examples/outputs/output-name-properties-get-200.json", the description is "SMPTE 2110-20 IP Output".
As 2110-20 is video only, I guess we wanted to reference an "ST2110-30" IP output.
Here's the link to the PR: #33

**Comment by peterbrightwell** [comment]
Resolved in #33 and merged
