### ISSUE TITLE
IS-08 Specification for the map/activation POST

### ISSUE THREAD

**Issue by a1800bert** [AMWA-TV/nmos-audio-channel-mapping#37]
Looking at the spec (https://amwa-tv.github.io/nmos-audio-channel-mapping/branches/v1.0.x/APIs/ChannelMappingAPI.html#map_activations_post) I don't see anything related to what to do, when ONE activation fails in the post.

Let say I have 3 activations, and one fail to business validation. I guess I have to reject the whole activation? Is it the case? It should be stipulated in the specs.

Also, it would have been nice to follow what IS05 had done with the BULK activation... it would have been easier to use the same kind of method, where one activation can be easily rejected...

**Comment by garethsb** [comment]
@a1800bert, is the documentation at https://amwa-tv.github.io/nmos-audio-channel-mapping/branches/v1.0.x/docs/4.0._Behaviour.html#activation-responses, clear? It seems to say that in any error scenario the API MUST reject the activation request in full with an appropriate 4xx code and helpful error json response.

**Comment by a1800bert** [comment]
I agree it is "clear" but somehow, so far from what IS05 offers, where 1 activation in the bulk can fail, and the other are processed. In IS08 if one activation on device X fails, but I was configuring device X-Y-Z I have to re-push Y-Z. It would have been nice that IS08 follow the same "format" as IS05.

**Comment by garethsb** [comment]
I see. Certainly IS-05 bulk activations were specified that way to avoid implementations having to perform roll-back. If this is also a concern for IS-08 implementations, I think this warrants further consideration in a future v1.1.

**Comment by VenkateswaranJ** [comment]
Any idea to support this in future?

**Comment by garethsb** [comment]
There isn't currently an Activity Group in the AMWA related to this spec. All Activity Groups start with user stories being discussed in the Incubator, and once they gain a few User and Vendor Proponents, then a proposal to create a formal Activity with a well defined scope, outputs and timeline, with sufficient engaged participants, can be presented to the NMOS Steering committee.

If you are keen to see this happen, start some discussions in the Incubator weekly calls or Slack channel.

**Comment by peterbrightwell** [comment]
Architecture Review Group review: closing. Please use Networked Media Incubator / #nmos-community slack to start discussions if further interest.
