### ISSUE TITLE
issue in io-response-shema.json

### ISSUE THREAD

**Issue by maxwalter79** [AMWA-TV/nmos-audio-channel-mapping#7]
in my opinion the **bold** marked regexp pattern in _io-response-schema.json_ schema is wrong. At least it does not match the example.
I guess it should be **"^[a-z A-Z 0-9 \\- _]+$"** as defined in _output-channels-response-schema.json_

>  "properties": {
>     "inputs":{
>       "type": "object",
>       "patternProperties": {
>         **"^[0-9]+:[0-9]+$"**:{
>           "type": "object",
>           "additionalProperties": false,
>           "properties": {
>             "parent":{
>               "$ref": "input-parent-response-schema.json"
>             },

regards, 
Max

**Comment by chris-gil** [comment]
Yes I agree, the pattern `^[0-9]+:[0-9]+$` is suitable for a timestamp rather than the id of an input.
The same issue applies to the outputs definition further on in the same file.
Your pattern of `^[a-z A-Z 0-9 \- _]+$` would allow for the full range of expected input/output identifiers including the use of dash and underscore:
- input1
- input-1
- input_01

**Comment by maxwalter79** [comment]
Another problem arose, as we tried to map our specific german (input/output) device names (with ä, ö, ü etc. in it) to NMOS lables.
This language special characters are not allowed with the current regexp. Is it a really good idea?
Why can't I have here same freedom of choice as e.g. by IS-04 node label which is a "Freeform string label for the resource"?

**Comment by simonrankine** [comment]
The former issue is clearly just a typo - I'll get that fixed ;)

The second issue is more interesting. The fix would be, I suppose, to allow any uni-code char. But that then means control systems have to handle all the funny control chars include all the control ones. Suggestions welcome...

**Comment by jasperpeeters** [comment]
Isn't that the case already with the label of any resource in IS-04 for example? I assume that no user would use an UUID directly for identification of a resource in an control application.

I think it is quite important to allow any uni-code character in this case.
However, per [RFC 3986](https://tools.ietf.org/html/rfc3986) you have to percent encode such non-ASCII characters if you want to use the label as part of the URI endpoint -- not sure if that can cause any issues. 
In that case it might be better to use UUIDs for Inputs / Outputs as identifier in view of the REST API endpoints and use the optional (freeform) label as additional info as seen in IS-04.

**Comment by simonrankine** [comment]
Closing this, as I think we've reached consensus on a way forward in calls, and should be all sorted in #16
