### ISSUE TITLE
Single activation object for map sufficient?

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-audio-channel-mapping#8]
Question: How to PATCH the map, if I want to apply a channel map (activating those) on multiple outputs in different ways, e.g.: 1 output relative first and than 1 output immediately?

We currently only have 1 "global" activation object on the map for all outputs.

Wouldn't it make more sense to move staged / active endpoints to the single outputs:
- `/outputs/{outputName}/staged`
- `/outputs/{outputName}/active`

**Comment by simonrankine** [comment]
While certainly possible, the reason I didn't do it that way in the first place is that if you have a device with a very large number of Inputs/Outputs you want to map in one hit you'd have to do a large number of requests to hit them all. So there is a compromise of flexibility vs scalability to be made I guess.

**Comment by simonrankine** [comment]
Resolved in #15
