### ISSUE TITLE
Source ID not optional in output-sourceID-response-schema.json

### ISSUE THREAD

**Issue by jasperpeeters** [AMWA-TV/nmos-audio-channel-mapping#9]
As written in the _Overview_ the source ID of an output is optional:
> Equivalent to the inputs resource but for Outputs - contains information about Output channels, restrictions on which Inputs may be routed to the Output, and an **optional** Source ID, which represents the new NMOS Source created by re-mapping the audio.

The [current json schema](https://github.com/AMWA-TV/nmos-audio-channel-mapping/blob/v1.0-dev/APIs/schemas/output-sourceID-response-schema.json) however does not allow this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "string",
  "description": "Gives an output's source ID",
  "title": "Output source ID resource",  
  "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
}
```

This should be modified to:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": ["string", "null"],
  "description": "Gives an output's source ID",
  "title": "Output source ID resource",  
  "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
  "default": null
}
```

@simonrankine Does it help to put these kind of small improvements directly into a PR?

**Comment by simonrankine** [comment]
Hi Jasper,

Agreed, null should be added. We've steered away from using `default` in more recent NMOS specs though, as it doesn't really have any useful meaning (either there's a source ID there or there isn't!).

But yes, PRs very welcome for small fixes like this :) However, just making this change myself now, so don't worry about it for this one.

Simon
